### ISSUE TITLE
getString error?

### ISSUE THREAD

**Issue by snihur** [RandomEtc/processing-gpx#1]
Hi,
I tried to run the nz_tracks example on my own linux box,
but I am getting the error below in processing 1.2.1.
Is it possible that getString should be replaced by getStringAttribute ?
http://forum.processing.org/topic/xmlelement-problem-function-getint-getstring-does-not-exist

thx,
-rob

Exception in thread "Animation Thread" java.lang.NoSuchMethodError: processing.xml.XMLElement.getString(Ljava/lang/String;)Ljava/lang/String;
        at tomc.gpx.GPXPoint.<init>(GPXPoint.java:63)
        at tomc.gpx.GPXTrackSeg.<init>(GPXTrackSeg.java:33)
        at tomc.gpx.GPXTrack.<init>(GPXTrack.java:36)
        at tomc.gpx.GPX.parse(GPX.java:67)
        at nz_tracks.setup(nz_tracks.java:36)
        at processing.core.PApplet.handleDraw(Unknown Source)
        at processing.core.PApplet.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:636)

**Comment by RandomEtc** [comment]
I've been testing in version 1.5.1 on a Mac and I don't have a Linux machine to hand, sorry. I'm not sure if anything changed in the XML library since 1.2.1?

I tested the nz_tracks file and it works fine here. I think there are some errors with the way I plotted the data, and you need to remove LINE_STRIP from the call to beginShape, but it works.
